### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by WaluigiBSOD** [WaluigiBSOD/dm64-password-tool#1]
# Code

- [x] When the user enters invalid arguments the program is designed to terminate with no visual information about the error, it only returns an error code. The program should also show something on-screen
- [x] Add a better error handler
- [x] Completely remove the "auto-test"
- [x] Check for grammatical errors in the comments of the source code
- [x] Optimize the code
- [x] Look for redundant/unnecessary validity checks and remove them
- [x] Add a CMakeLists.txt

# Documentation

- [x] Add code documentation generated with Doxygen
- [x] Add an empty `.nojekyll` file in the root of the website
- [x] Add a `404.html` 404 error handler in the root of the website that redirects to the main page

# Repository

- [x] Move the source code into a subfolder
